aksio-insurtech/IngressMiddleware

- .github/README.md
- .github/workflows/dotnet-build.yml
- .github/workflows/publish.yml
- .github/workflows/pull-requests.yml
- Docker/Development/Dockerfile
- Docker/Production/Dockerfile
- Fixing wrongly configured docker files and GitHub actions configuration.
> Fixing wrong folder names + removing workbench

- Source/Program.cs
- Making configuration optional.
> Make config optional

- Source/HttpHelper.cs
- Source/IngressMiddleware.csproj
- Source/Program.cs
- Source/appsettings.Development.json
- Source/appsettings.json
> Adding logging

- Source/OpenIDConnect.cs
- Setting the correct callback for the code exchange.
> Adding callback

- Source/Origin.cs
- Configuring origin cookie with more properties for testing.
> Adding more cookie settings for testing

- Source/HttpHelper.cs
- Source/IdPorten.cs
- Source/Program.cs
- Source/QueryCollectionExtensions.cs
> Cleaning up - taking out unused code

- Source/Cratis.cs
- Source/IngressMiddleware.csproj
- Source/TenantConfig.cs
- Adding support for setting Tenant-ID header based on TID claim.
> Adding support for mapping tenant to tenant Id claims

- Source/Cratis.cs
- Adding logging to see which Tenant-ID gets set for a request.
> Adding logging for Tenant-ID

- Docker/Development/Dockerfile
- Adding the static files for the toolbar into the development image.
> Adding wwwroot to development image

- Source/Identity.cs
- Removing sensitive data from log output.
> Reducing log volume to avoid logging sensitive information

- Source/Identity.cs
- Adding log message to see the principal information
> Adding a log for debugging purposes of Identity

- Source/Identity.cs
- Removing the requirement of `x-ms-client-principal-id` and `x-ms-client-principal-name` for calling the `.aksio/me` endpoint.
> Removing PrincipalId and PrincipalName as requirements for a valid principal

- Source/Identity.cs
- Adding forwarding of `Tenant-ID` header to the identity provider.
> Forward tenant id

- .vscode/settings.json
- README.md
- Source/AuthorityResult.cs
- Source/Config.cs
- Source/Headers.cs
- Source/IngressMiddleware.csproj
- Source/OAuthBearerTokens.cs
- Source/OAuthBearerTokensConfig.cs
- Source/Program.cs
- Source/appsettings.Development.json
- Adding support for OAuth bearer tokens authorization.
> Adding support for OAuth Bearer Tokens

- .github/workflows/pull-requests.yml
- Source/IngressMiddleware.csproj
- Versions.props
- Updated Cratis packages to support Aksio.Cratis.Applications.Logging.RenderedCompactJsonFormatter which is the desired format in Aksio cloud-deployed systems.
- Bumped token NuGet packages
> Updated Cratis packages to support logformat

- README.md
- Source/ClaimsSourceIdentifierResolver.cs
- Source/ClaimsSourceIdentifierResolverOptions.cs
- Source/Config.cs
- Source/Globals.cs
- Source/Headers.cs
- Source/ITenantSourceIdentifierResolver.cs
- Source/Program.cs
- Source/RouteSourceIdentifierResolver.cs
- Source/RouteSourceIdentifierResolverOptions.cs
- Source/Tenancy.cs
- Source/TenantConfig.cs
- Source/TenantResolutionConfig.cs
- Source/TenantResolutionRouteOptions.cs
- Source/TenantSourceIdentifierResolver.cs
- Source/TenantSourceIdentifierResolverType.cs
- Source/config/config.json
- Support for resolving tenant source identifiers from routes.
- Configuration for resolving tenancy from claims.
> Up and running with more flexible solution for tenant resolution + route support

- Source/Identities/IIdentityDetailsResolver.cs
- Source/Identities/IdentityDetailsResolver.cs
- Source/Impersonation/Impersonator.cs
- Specifications/for_RequestAugmenter/when_handling_impersonated_route.cs
- Specifications/for_RequestAugmenter/when_handling_impersonation_route.cs
- Specifications/for_RequestAugmenter/when_handling_non_impersonated_route_and_identity_provider_requires_impersonation.cs
- Specifications/for_RequestAugmenter/when_handling_regular_route_and_all_is_valid.cs
- Specifications/for_RequestAugmenter/when_handling_regular_route_and_bearer_token_is_not_authorized.cs
- Specifications/for_RequestAugmenter/when_handling_regular_route_that_fails_identity_resolution.cs
- Allowing for overriding the resolution of identities when doing impersonation.
> Support resolving identities when doing impersonation

- Source/Identities/IdentityDetailsResolver.cs
- Fixing the check for the identity resolver while we're doing impersonation to go through.
> Moving the paranthesis :)

- README.md
- Specifications/for_MutualTLS/when_handling_a_mtls_client_with_wrong_serialnumber.cs
- Documentation for mTLS/Client Certificates.
- Minor test tweak.
> Added mutualTLS information to README.md

- Directory.Packages.props
- Source/BearerTokens/IOAuthBearerTokens.cs
- Source/BearerTokens/OAuthBearerTokens.cs
- Source/Identities/IIdentityDetailsResolver.cs
- Source/Identities/IdentityDetailsResolver.cs
- Source/Identities/IdentityDetailsResolverLogMessages.cs
- Source/Impersonation/ImpersonationFlow.cs
- Source/IngressMiddleware.csproj
- Source/Program.cs
- Source/Tenancy/ITenantResolver.cs
- Source/Tenancy/TenantResolver.cs
- Specifications/Impersonation/for_ClaimImpersonationAuthorizer/when_asking_if_authorized/and_no_claims_filters_are_configured.cs
- Specifications/Impersonation/for_IdentityProviderImpersonationAuthorizer/when_asking_if_authorized/and_there_are_no_identity_providers_configured.cs
- Specifications/Impersonation/for_TenantImpersonationAuthorizer/when_asking_if_authorized.cs/with_two_tenant_filters_and_request_matching_one_of_them.cs
- Specifications/Impersonation/for_TenantImpersonationAuthorizer/when_asking_if_authorized.cs/with_two_tenant_filters_and_request_not_matching_any_of_them.cs
- Specifications/Tenancy/for_TenantResolver/when_resolving/and_resolver_resolves_it.cs
- Specifications/for_RequestAugmenter/given/a_request_augmenter.cs
- Updated Aksio Application and Fundamentals NuGet packages
- Added MutualTLS to service locator during startup.
> Aksio NuGet package update and startup configfix

- Source/MutualTLS/MutualTLS.cs
- Source/MutualTLS/MutualTLSLogMessages.cs
- Changed some logging in mTLS handling.
> Improved logging when handling mTLS

- Source/RoleAuthorization/RoleAuthorizer.cs
- Source/Tenancy/SourceIdentifierResolvers/ClaimsSourceIdentifier.cs
- Specifications/Tenancy/for_SourceIdentifierResolver/given/a_sourceidentifier_resolver.cs
- Specifications/integrationtests/role_authorization/given/factory_with_host_resolution_and_role_auth_with_scoped_tenancyresolution.cs
- Specifications/integrationtests/role_authorization/given/factory_with_role_auth_with_scoped_tenancyresolution.cs
- Specifications/integrationtests/routeSourceIdentifierResolver/given/route_source_specification.cs
- Specifications/integrationtests/route_and_then_claim_sourceidentifier/given/multi_resolution_host.cs
> Name cleanup
